### ISSUE TITLE
Failed to build gem native extension OSX 10.10.3

### ISSUE THREAD

**Issue by stats** [knu/ruby-unf_ext#11]
running:

    gem install unf_ext -v '0.0.7.1'

results in the following error

    ERROR:  Error installing unf_ext:
	ERROR: Failed to build gem native extension.

    [snip]/rubies/ruby-1.9.3-p547/bin/ruby extconf.rb checking for main() in -lstdc++...     *** extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of necessary libraries and/or headers.  Check the mkmf.log file for more details.  You may need configuration options.

The stack trace is: 

    [snip]/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
    You have to install development tools first.
	from [snip]/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:461:in `try_link0'
	from [snip]/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:476:in `try_link'
	from [snip]/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:619:in `try_func'
	from [snip]/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:845:in `block in have_library'
	from [snip]/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:790:in `block in checking_for'
	from [snip]/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:284:in `block (2 levels) in postpone'
	from [snip]/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:254:in `open'
	from [snip]/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:284:in `block in postpone'
	from [snip]/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:254:in `open'
	from [snip]/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:280:in `postpone'
	from [snip]/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:789:in `checking_for'
	from [snip]/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:840:in `have_library'
	from extconf.rb:6:in `<main>'

A number of similar issues discuss installing different versions of command line tools. I downgraded to 6.2 and then reupgraded to 6.3 and 6.3.1 with no change.

My xcode-select version is 2339, and I just did a complete install of xcode 6.3.1 with no change.

**Comment by matthuhman** [comment]
I'm having the same issue right now. Is there currently a fix that avoids downgrading to 6.2?

**Comment by stats** [comment]
I was able to resolve this issue, and I think it was related to the state of brew following the upgrading to Yosemite.

1. Uninstall Brew
2. Reinstall Brew
3. Uninstall ruby
4. Reinstall ruby
5. Install bundler
6. Run bundle update
