### ISSUE TITLE
fails to build on ruby-head(2.3.0)

### ISSUE THREAD

**Issue by ashleygwilliams** [knu/ruby-unf_ext#12]
working on getting [sintra-contrib](https://github.com/sinatra/sinatra-contrib) green in ruby-head

machine: debian(jessie), ruby-head(2.3.0) 
error output and `mkmf.log` here: https://gist.github.com/ashleygwilliams/97dc7eb34f43fdbf3952

any help would be appreciated!

**Comment by zzak** [comment]
@nobu fixed this here: https://github.com/ruby/ruby/commit/356baf95db7162b5a964dd17a8fe871afe805cf5

**Comment by ashleygwilliams** [comment]
woo!fix confirmed :)
