### ISSUE TITLE
Release new gem (post-0.0.7.2) with ARM fixes, new Unicode 9 support

### ISSUE THREAD

**Issue by vielmetti** [knu/ruby-unf_ext#26]
Now that #15 has been committed, the next step is to cut a new bug fix release that would include the ARM changes and that would in turn allow Ruby code that uses `unf_ext` to be ported to ARM (Raspberry Pi, ThunderX, and a bunch of systems in between) without doing anything special for this gem.

In addition, it would be sensible to incorporate in the updates from upstream that bring in support for Unicode 9, see #29 for that issue.

**Comment by terceiro** [comment]
Hi, this issue affectiing ARM also affects other architectures, such as ppc46el (64-bit PowerPC Little-Endian, aka POWER). See [this Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=859463) for details.

It would indeed be very nice to have a new release with this fix, and if possible, with #27 merged as well.

**Comment by vielmetti** [comment]
Added a release question for Unicode 9 support.

**Comment by knu** [comment]
Just released 0.0.7.3.
