### ISSUE TITLE
Only supports Unicode 6.0, while upstream `unf` supports 9.0

### ISSUE THREAD

**Issue by nomoon** [knu/ruby-unf_ext#29]
Unicode 9.0 support and test data has been accepted upstream in sile/unf#1. All this entails is updating the `table.hh` and `normalization-test.txt` files.

Fixed by #24 (although that PR needs an update to the `table.hh` to match whatever type signedness fixes are happening in these other recent PRs)

**Comment by knu** [comment]
Thanks for the notice.  Done.
