### ISSUE TITLE
Support for Ruby Version 2.5.0

### ISSUE THREAD

**Issue by garrit-schroeder** [knu/ruby-unf_ext#36]
Hello Guys,
are you planning on releasing a new version for Ruby 2.5.0?

Thanks a lot.

Greetings
Garrit

**Comment by nomoon** [comment]
Are you receiving a particular error?

**Comment by msg7086** [comment]
x64-mingw32 and x86-mingw32 requires `RUBY VERSION: < 2.5, >= 2.0` on Windows.

**Comment by knu** [comment]
Just released 0.0.7.5, in which Windows binary gems include unf_ext.so for 2.5.0.
