### ISSUE TITLE
0.0.7.5 Fails to install on MacOS 10.13.2 with Ruby 1.9.3

### ISSUE THREAD

**Issue by fatmcgav** [knu/ruby-unf_ext#38]
When updating some of my Ruby projects today, I got a Gem install failure on the `unf_ext 0.0.7.5`.

The exception and associated mkmf.log is available here: https://gist.github.com/fatmcgav/973fe8d8210bd3ae7ab23faa457d6c50

Let me know if I can provide any further info. 

Edit: Probably worth adding that v0.0.7.5 version installed fine on a CentOS 7 VM, so hence my suspicion that this is a MacOS related bug...

**Comment by knu** [comment]
Without string.h (as claimed in the log) you'd not be able to compile almost anything.  Maybe you need to run `xcode-select --install` or something is wrong with your Xcode/Command Line Tools installation.

**Comment by fatmcgav** [comment]
@knu It looks like there is something screwy with my Xcode setup... Apologies for the noise...
