### ISSUE TITLE
Ruby 2.6 x86-mingw32 support

### ISSUE THREAD

**Issue by z64** [knu/ruby-unf_ext#48]
Hi there! Ruby 2.6 is here, and the `x86-mingw32` release on rubygems is bound to `< 2.6`.

https://rubygems.org/gems/unf_ext/versions/0.0.7.5-x86-mingw32

I don't have a development `x86-mingw32` machine to test Ruby 2.6 compatibility myself, so I would appreciate your help in adding support and releasing new packages. Our gem relies on `unf_ext`, and we have a good number of Windows users 🙂 

Let me know if there's anything I can do to help, or if you need any more information.

**Comment by swarley** [comment]
I built the gem an ran tests locally for `ruby 2.6.1p33 (2019-01-30 revision 66950) [x64-mingw32]` and `i386-mingw32`. All tests passed with no modification necessary.

**Comment by psubrownie** [comment]
PR #47 fixes this issue, it just needs merged

**Comment by swarley** [comment]
Presently in lieu of changes upstream, anyone that is having an issue with this can refer to [this post](https://github.com/meew0/discordrb/issues/604#issuecomment-475913239) on potential work arounds

**Comment by z64** [comment]
Looks like there has been a new release that relaxes the requirements on the gem package. Thank you! :cat:

**Comment by orgads** [comment]
Does it work for you? See #52.
