### ISSUE TITLE
Latest version doesn't contain a binary for Windows

### ISSUE THREAD

**Issue by orgads** [knu/ruby-unf_ext#52]
In rubygems, version 0.0.7.6 doesn't have binary packages:

```
0.0.7.6 - April 20, 2019 (390 KB)
0.0.7.5 - February 06, 2018 x64-mingw32 (6.35 MB)
0.0.7.5 - February 06, 2018 x86-mingw32 (6.07 MB)
0.0.7.5 - February 06, 2018 (390 KB)
```

**Comment by trevormccasland** [comment]
This has happened for the past two releases, is this intentional?

**Comment by glennsarti** [comment]
11 months on and still no builds?  What's going on ?

**Comment by ronaldtse** [comment]
It seems that we won't be able to use unf_ext until this is fixed. 

This commit (https://github.com/knu/ruby-unf_ext/commit/90fd38bfd32784bfc5f7a7d74d70da7707fa56a2) from @knu claims that there are Windows binaries for 2.6, but they are not in RubyGems?

**Comment by knu** [comment]
Just pushed 0.0.7.7!

**Comment by johnnyshields** [comment]
This is done -- can be closed.
