### ISSUE TITLE
Is version 0.0.7.7 a legitimate release?

### ISSUE THREAD

**Issue by orien** [knu/ruby-unf_ext#55]
I see a new release has been pushed to RubyGems.org https://rubygems.org/gems/unf_ext/versions/0.0.7.7 but there's no corresponding changes in this repository, with no commits since 2019-04-20!

@knu could you please confirm this is a legitimate release. I'm concerned this release contains a malicious payload.

**Comment by knu** [comment]
Thanks for the heads-up.  I pushed the tag but just forgot to push to master.  It is now settled!

**Comment by orien** [comment]
Thanks @knu!
