### ISSUE TITLE
Push tag v0.0.7.7

### ISSUE THREAD

**Issue by MITSUBOSHI** [knu/ruby-unf_ext#56]
Hi, it seems unf_ext v0.0.7.7 is available.
https://rubygems.org/gems/unf_ext/versions/0.0.7.7
However, there is no tags for v0.0.7.7 on GitHub. Could you please push it?

**Comment by josepbordesjove** [comment]
Any news with this?

**Comment by pravi** [comment]
@knu I'd like to update the debian package to this new version and pushing tag for this version would help there.

**Comment by knu** [comment]
Sorry, better late than never, done!
