### ISSUE TITLE
0.0.8.2 binary builds seemed to be tagged as "beta"?

### ISSUE THREAD

**Issue by johnnyshields** [knu/ruby-unf_ext#68]
From Rubygems release page: https://rubygems.org/gems/unf_ext/versions

![image](https://user-images.githubusercontent.com/27655/170467554-764201ff-121f-4cb3-8867-c8a0a1f206de.png)

**Comment by johnnyshields** [comment]
@knu can you please check this?

**Comment by knu** [comment]
Oh, I think I forgot to push binary gems.  Just pushed those, so please check out.

**Comment by johnnyshields** [comment]
@knu perfect, thank you!
