### ISSUE TITLE
Install on MacOS 10.9.5 -- Issues with bundle install and Ruby 1.9.3

### ISSUE THREAD

**Issue by keithnickas** [knu/ruby-unf_ext#9]
I have been trying to get the gem to install using bundle but I'm never able to get very far. It seems to install when I use `gem` or `bundle install --gemfile=`  but when I attempt to do the regular `bundle install` for my app it results in the following:

```
/Users/user-folder/.rbenv/versions/1.9.3-p327/bin/ruby extconf.rb
checking for main() in -lstdc++... yes
checking for ruby/encoding.h... yes
creating Makefile

make
compiling unf.cc
cc1plus: warning: command line option ‘-Wdeclaration-after-statement’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wimplicit-function-declaration’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from unf.cc:1:0:
unf/normalizer.hh:4:18: fatal error: vector: No such file or directory
compilation terminated.
make: *** [unf.o] Error 1
```

Another error that I get is the following when I use the other bundle install method above:
`Could not find unf_ext-0.0.6 in any of the sources`

I haven't been able to track down a definitive source of the problem, although I have updated python, update xCode and GCC to 4.6.2 ... sorta at a loss as to where I should go from here--any guidance would be truly appreciated.

**Comment by stats** [comment]
This may be an issue with the state of brew/ruby. I was able to fix a similar issue by reinstall brew and ruby. https://github.com/knu/ruby-unf_ext/issues/11

**Comment by gertig** [comment]
This may also be due to not having agreed to the Xcode license agreements. I had this same issue and after launching Xcode and agreeing to the license agreement the problem was solved.

**Comment by robotmay** [comment]
@gertig's solution solved this for me too. Probably one of the weirdest install solutions I've had work!

**Comment by gertig** [comment]
@robotmay I thought it was pretty weird too, almost decided against posting that comment in case I was crazy. Glad it helped!
